before_script:
  # Exit one errors.
  - set -e

  # Install webdriverCSS
  - cd ./visual-monitor
  - npm install
  - cd ..


script:
  - cd ./visual-monitor
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
